# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: note-app-frontend-service
spec:
  selector:
    app: note-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the frontend to the internet
